In [2]:
import tensorflow as tf
print(tf.__version__)

2.4.0


In [3]:
mnist = tf.keras.datasets.fashion_mnist

In [4]:
(training_images, training_labels), (test_images, test_labels) = mnist.load_data()

In [5]:
import numpy as np
np.set_printoptions(linewidth=200)
import matplotlib.pyplot as plt
plt.imshow(training_images[40])
print(training_labels[40])
print(training_images[40])

6
[[  0   0   0   0   0   0   0   0   1   0   0  37 192 177 171 199  27   0   0   0   1   3   0   0   0   0   0   0]
 [  0   0   0   0   0   0   9   0   0   0   0 135 230 162 155 253 164  14   0   0   0   0   3   0   0   0   0   0]
 [  0   0   0   0   1   0   0   0  64 152 232 207 195 155 157 201 227 224 221 172  94   4   0   0   0   0   0   0]
 [  0   0   0   0   0   0 112 179 205 199 192 197 216 194 192 220 210 192 191 203 207 208  62   0   1   0   0   0]
 [  0   0   0   0   0  75 208 186 178 185 172 197 213 195 200 208 199 188 187 181 180 204 192   0   0   0   0   0]
 [  0   0   0   0   0 180 190 179 185 182 184 178 166 193 185 167 187 186 184 184 192 192 223  28   0   0   0   0]
 [  0   0   0   0   0 205 190 182 182 185 182 185 181 182 180 180 185 186 182 184 201 195 219  72   0   0   0   0]
 [  0   0   0   0   0 210 186 194 181 181 182 178 180 184 182 177 179 185 184 194 211 188 218  95   0   0   0   0]
 [  0   0   0   0   0 217 179 193 193 175 175 174 178 182 184 174 177 177 186 

In [6]:
training_images = training_images /255.0
test_images = test_images / 255.0

In [7]:
model = tf.keras.models.Sequential([tf.keras.layers.Flatten(),
                                  tf.keras.layers.Dense(128, activation=tf.nn.relu),
                                  tf.keras.layers.Dense(10, activation=tf.nn.softmax)])

In [8]:
model.compile(optimizer = tf.optimizers.Adam(),
             loss = 'sparse_categorical_crossentropy',
             metrics=['accuracy'])
model.fit(training_images, training_labels, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.6337 - accuracy: 0.7819
Epoch 2/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.3900 - accuracy: 0.8621
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3356 - accuracy: 0.8766
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.3151 - accuracy: 0.8850
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.2892 - accuracy: 0.8929


In [9]:
model.evaluate(test_images, test_labels)

313/313 [==============================] - 1s 1ms/step - loss: 0.3572 - accuracy: 0.8734


[0.3572087585926056, 0.8733999729156494]

# Exploration Exercises

# 20210107 Fri

In [10]:
classifications = model.predict(test_images)
print(classifications[0])

[8.71992086e-07 1.08477245e-07 1.73241034e-07 7.40514281e-08 4.21990478e-07 9.96909663e-03 3.88236595e-06 1.92296188e-02 8.74096149e-05 9.70708311e-01]


In [11]:
print(test_labels[0])

9


# Exercise 2:

In [12]:
import tensorflow as tf
print(tf.__version__)

2.4.0


In [19]:
mnist = tf.keras.datasets.mnist
(training_images, training_labels), (test_images, test_labels) = mnist.load_data()
training_images = training_images/255.0
test_images = test_images/255.0

model = tf.keras.models.Sequential([tf.keras.layers.Flatten(),
                                   tf.keras.layers.Dense(512, activation=tf.nn.relu),
                                   tf.keras.layers.Dense(10, activation=tf.nn.softmax)])

model.compile(optimizer = 'adam',
             loss = 'sparse_categorical_crossentropy')

model.fit(training_images, training_labels, epochs=5)

model.evaluate(test_images, test_labels)

Epoch 1/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.3419
Epoch 2/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0821
Epoch 3/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0520
Epoch 4/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0337
Epoch 5/5
313/313 [==============================] - 1s 1ms/step - loss: 0.0745


0.07452172785997391

In [18]:
classifications = model.predict(test_images)

print(classifications[0])
print(test_labels[0])

[4.4675721e-10 2.6535821e-13 2.3657867e-10 7.6985594e-07 1.1349764e-17 1.0872991e-09 6.1873566e-17 9.9999928e-01 4.2996314e-12 1.2994021e-09]
7


# Exercise 3:

In [20]:
import tensorflow as tf
print(tf.__version__)

2.4.0


In [21]:
mnist = tf.keras.datasets.mnist

In [22]:
(training_images, training_labels), (test_images, test_labels) = mnist.load_data()

In [23]:
training_images = training_images/255.0
test_images = test_images/255.0

In [47]:
model = tf.keras.models.Sequential([tf.keras.layers.Flatten(),
                                    tf.keras.layers.Dense(128, activation=tf.nn.relu),
                                    tf.keras.layers.Dense(10, activation=tf.nn.softmax)])

In [48]:
model.compile(optimizer = 'adam',
             loss = 'sparse_categorical_crossentropy')
model.fit(training_images, training_labels, epochs=30)

Epoch 1/30
1875/1875 [==============================] - 3s 1ms/step - loss: 0.4435
Epoch 2/30
1875/1875 [==============================] - 3s 1ms/step - loss: 0.1184
Epoch 3/30
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0775
Epoch 4/30
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0597
Epoch 5/30
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0450
Epoch 6/30
1875/1875 [==============================] - 3s 1ms/step - loss: 0.0327
Epoch 7/30
1875/1875 [==============================] - 3s 1ms/step - loss: 0.0263
Epoch 8/30
1875/1875 [==============================] - 3s 1ms/step - loss: 0.0226
Epoch 9/30
1875/1875 [==============================] - 3s 1ms/step - loss: 0.0179
Epoch 10/30
1875/1875 [==============================] - 3s 1ms/step - loss: 0.0127
Epoch 11/30
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0129
Epoch 12/30
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0102A:

In [49]:
model.evaluate(test_images, test_labels)

313/313 [==============================] - 0s 1ms/step - loss: 0.1191


0.11909593641757965

In [50]:
classifications = model.predict(test_images)

In [51]:
print(classifications[0])
print(test_labels[0])

[7.6634688e-15 1.8409975e-19 4.4460658e-15 5.8209904e-12 7.2963311e-26 2.8703162e-19 8.8316955e-33 1.0000000e+00 9.2179012e-19 7.7682544e-14]
7


# Exercise 8:

In [52]:
import tensorflow as tf
print(tf.__version__)

2.4.0


In [53]:
class myCallback(tf.keras.callbacks.Callback):
    def on_epoch_end(self, epoch, logs={}):
        if(logs.get('loss')<0.4):
            print("\nReached 60% accuracy so canceling training!")
            self.model.stop_training = True

In [54]:
callbacks = myCallback()
mnist = tf.keras.datasets.fashion_mnist
(training_images, training_labels), (test_images, test_labels) = mnist.load_data()
training_images = training_images/255.0
test_images=test_images/255.0

In [55]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(512, activation=tf.nn.relu),
    tf.keras.layers.Dense(10, activation=tf.nn.softmax)
])

In [56]:
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy')
model.fit(training_images, training_labels, epochs=5, callbacks=[callbacks])

Epoch 1/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.5894
Epoch 2/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.3619

Reached 60% accuracy so canceling training!
